# Use root/example as user/password credentials
version: '3'

services:

  db:
    image: "mysql:5.7.11"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: face
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes: 
      - ./dbdata:/docker-entrypoint-initdb.d
  web:
    # image: "xiantm/face_service"
    build: 
      context: .
    depends_on:
      - db
    restart: always
    ports:
      - "5000:5000"
    environment: 
      IN_DOCKER: "yes"

  